ensure_bootstrap: error out if any arguments are passed in
Running with --help shouldn't actually do the bootstrap.

Change-Id: Id481432cdfc23121e5b71cbe64ffb2068fea8e23

diff --git a/ensure_bootstrap b/ensure_bootstrap
--- a/ensure_bootstrap
+++ b/ensure_bootstrap
@@ -14,6 +14,11 @@
 # invoke this script instead of manually calling "cipd_bin_setup" and other
 # operations.
 
+if [ $# -ne 0 ]; then
+  echo "$0: ERROR: script takes no arguments" >&2
+  exit 1
+fi
+
 # Export for other depot_tools scripts to re-use.
 export DEPOT_TOOLS_DIR="${DEPOT_TOOLS_DIR:-$(dirname "${BASH_SOURCE[0]}")}"
 
